// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaAnagrafica.Models;

namespace ProvaAnagrafica.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ProvaAnagrafica.Models.Anagrafica", b =>
                {
                    b.Property<int>("AnagraficaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnoNascita");

                    b.Property<string>("CodiceFiscale");

                    b.Property<string>("Cognome");

                    b.Property<string>("Nome");

                    b.Property<char>("Sesso");

                    b.HasKey("AnagraficaId");

                    b.ToTable("Anagrafiche");
                });

            modelBuilder.Entity("ProvaAnagrafica.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("ProvaAnagrafica.Models.Indirizzo", b =>
                {
                    b.Property<int>("IndirizzoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnagraficaId");

                    b.Property<int>("CAP");

                    b.Property<string>("Città");

                    b.Property<string>("Nazione");

                    b.Property<string>("NomeIndirizzo");

                    b.HasKey("IndirizzoId");

                    b.HasIndex("AnagraficaId");

                    b.ToTable("Indirizzi");
                });

            modelBuilder.Entity("ProvaAnagrafica.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<int?>("IndirizzoId");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.HasIndex("IndirizzoId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ProvaAnagrafica.Models.Indirizzo", b =>
                {
                    b.HasOne("ProvaAnagrafica.Models.Anagrafica", "Anagrafica")
                        .WithMany("Indirizzi")
                        .HasForeignKey("AnagraficaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProvaAnagrafica.Models.Post", b =>
                {
                    b.HasOne("ProvaAnagrafica.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProvaAnagrafica.Models.Indirizzo")
                        .WithMany("Posts")
                        .HasForeignKey("IndirizzoId");
                });
#pragma warning restore 612, 618
        }
    }
}
